### PR TITLE
fix / in define for 1/60 Hz

### PR DESCRIPTION
**Pull request by tbjers**
Not trying to touch anything outside of the broken define, hence a separate PR from #17.

### CODE REVIEW

**Comment by gtjoseph** [comment]
I just ran into the same issue using the ESP-IDF and Arduino-esp32.

**Comment by adamgarbo** [comment]
Thanks for the PR @tbjers

@AndyEngland521 are you still looking after the RTC libraries? It'd be good to get the outstanding PRs merged.

**Comment by nseidle** [comment]
Many thanks for the PR @tbjers. I should be able to look at the RV-8803 PRs this week.

**Comment by nseidle** [comment]
Nice fix. Thanks for the PR! Merging.

**Pull request merged**
